//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ReadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bugs
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Status_Value { get; set; }
        public int Severity_Value { get; set; }
        public int Priority_Value { get; set; }
    }
}
