//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ReadModel
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestWorkshopEntities : DbContext
    {
        public TestWorkshopEntities(string connectionString)
            : base("metadata = res://*/ReadModel.ReadModel.csdl|res://*/ReadModel.ReadModel.ssdl|res://*/ReadModel.ReadModel.msl;"
                  +"provider=System.Data.SqlClient;" 
                  +$"provider connection string=\"{connectionString};"
                  +"App=EntityFramework\";")
        { }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BugHistories> BugHistories { get; set; }
        public virtual DbSet<Bugs> Bugs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
